version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'

  oracle12:
    image: 'sath89/oracle-12c'
    environment:
      - WEB_CONSOLE=false
    ports:
      - '8080:8080'
      - '1521:1521'
    volumes:
       - ./oracle/data:/u01/app/oracle
       - ./oracle/init.d:/docker-entrypoint-initdb.d

  oracle12-volume:
    image: twyn/oracle12-volume
    volumes:
      - /tmp/oracle12-volume/data:/data


