version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "velocity2"

    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./postgres/init.d:/docker-entrypoint-initdb.d/"

volumes:
   db-data:
