apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: cloudhealth
    rules:
    - apiGroups: [""]
      resources:
        - "pods"
        - "nodes"
        - "services"
      verbs: ["get", "watch", "list"]
  - apiVersion: v1
    kind: ServiceAccount
    metadata: {
      name: cloudhealth,
    }
    automountServiceAccountToken: true
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: cloudhealth
    subjects:
    - kind: ServiceAccount
      name: cloudhealth
      namespace: default
    roleRef:
      kind: ClusterRole
      name: cloudhealth
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: Pod
    metadata:
      name: cloudhealth-collector
      namespace: default
      labels:
        name: cloudhealth-collector
    spec:
      serviceAccountName: cloudhealth
      automountServiceAccountToken: true
      containers:
        - name: cloudhealth-collector
          image: cloudhealth/container-collector:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: ".5"
            limits:
              memory: "1024Mi"
              cpu: "1"
          env:
            - name: CHT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudhealth-config
                  key: api-token
            - name: CHT_CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudhealth-config
                  key: cluster-name
            - name: CHT_INTERVAL
              value: "900"
            - name: CHT_JVM_MEM
              value: "-Xmx891M"
          args: ["upload_k8s_state", "--verbose"]
      restartPolicy: Always
